name: Feature Request
description: Suggest an idea for this project
title: "Request "
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-info
    attributes:
      label: Describe your request
      description: A clear and concise description of what you like us to add.
      placeholder: Tell us about your idea!
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
    validations:
      required: false